[general]
static=yes
writeprotect=no

[from-internal]
; Echo test (Dial *43 to test audio bi-directionally)
exten => *43,1,Answer()
 same => n,Wait(1)
 same => n,Playback(demo-echotest)
 same => n,Echo()
 same => n,Hangup()

; Calling extension 101
exten => 101,1,Dial(PJSIP/101,30)
 same => n,Hangup()
